#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from All_Functions import pattern_count


Text = "ATTGGTCGGGAGCGTGTTTTTTAGCTGCTACGGATGAGCGTGTTGTATGGAGAGCGTGTTATTGGTCGGCTACGGATGAGCGTGTTCTACGGATGAGCGTGTTGTATGGATTTTAGCTGTTTTAGCTGTTTTAGCTGGAGCGTGTTGAGCGTGTTTTTTAGCTGGTATGGAGTATGGATTTTAGCTGATTGGTCGGGTATGGACTACGGATCTACGGATGAGCGTGTTGTATGGAATTGGTCGGCTACGGATTTTTAGCTGGAGCGTGTTCTACGGATGAGCGTGTTTTTTAGCTGCTACGGATTTTTAGCTGATTGGTCGGCTACGGATATTGGTCGGTTTTAGCTGGTATGGACTACGGATTTTTAGCTGTTTTAGCTGGAGCGTGTTTTTTAGCTGGAGCGTGTTGTATGGACTACGGATGTATGGACTACGGATCTACGGATTTTTAGCTGGTATGGAATTGGTCGGTTTTAGCTGATTGGTCGGATTGGTCGGCTACGGATCTACGGATGTATGGAGAGCGTGTTTTTTAGCTGGTATGGAGTATGGAGTATGGAGAGCGTGTTCTACGGATATTGGTCGGCTACGGATGAGCGTGTTGAGCGTGTTATTGGTCGGGAGCGTGTTGAGCGTGTTTTTTAGCTGGTATGGATTTTAGCTGTTTTAGCTGGTATGGAATTGGTCGGATTGGTCGGATTGGTCGGTTTTAGCTGGTATGGACTACGGATGAGCGTGTTGTATGGACTACGGATGTATGGACTACGGATTTTTAGCTGGTATGGAATTGGTCGGGAGCGTGTTGTATGGACTACGGATTTTTAGCTGATTGGTCGGCTACGGATTTTTAGCTGCTACGGATGTATGGACTACGGATTTTTAGCTG"
k = 14

def FrequentWords(Text, k):
    FrequentPatterns = set()  # to store the frequent k-mers
    Count = [0] * (len(Text) - k + 1)  # count for ea. k-mer
    
    for i in range(len(Text) - k + 1): # 
        Pattern = Text[i:i+k]  # extract the pattern
        Count[i] = pattern_count(Text, Pattern)  # count occurances of the k-mer
    
    maxCount = max(Count)
    
    for i in range(len(Text) - k + 1):     #find all k-mers w/ max count
        if Count[i] == maxCount:
            FrequentPatterns.add(Text[i:i+k])  # add k-mer to the set
    
    return FrequentPatterns


# call the function & print the output
result = FrequentWords(Text, k)
print(" ".join(result)) 
 